services:
  evrinoma.system.shell:
    class: Evrinoma\SystemBundle\Shell\Shell

  Evrinoma\SystemBundle\Shell\Shell:
    alias: evrinoma.system.shell
    public: true

  Evrinoma\SystemBundle\Shell\ShellInterface:
    alias: evrinoma.system.shell
    public: true
